# Generated by Django 6.0.7 on 2026-08-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covalentuser',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('VENDOR', 'Vendor'), ('LAWYER', 'Lawyer')], default='BUYER', max_length=10),
        ),
    ]
