# Generated by Django 6.0.7 on 2026-07-16 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_covalentuser_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('vendor_email', models.EmailField(help_text='Email of the vendor selling the item', max_length=254)),
                ('item_title', models.CharField(max_length=200)),
                ('item_description', models.TextField()),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_escrow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plain_language_summary', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_FUNDING', 'Awaiting Funding'), ('FUNDED', 'Funded & Active'), ('RELEASED', 'Completed')], default='DRAFT', max_length=30)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
