# Generated by Django 6.0.7 on 2026-07-16 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dispute_disputeevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='covalentuser',
            name='is_lawyer',
            field=models.BooleanField(default=False, help_text='Designates user as a verified arbitration reviewer'),
        ),
        migrations.AddField(
            model_name='covalentuser',
            name='lawyer_cases_resolved',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArbitrationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruling', models.CharField(choices=[('BUYER', 'Rule for Buyer (Refund Escrow)'), ('VENDOR', 'Rule for Vendor (Release Escrow)')], max_length=10)),
                ('legal_justification', models.TextField(help_text='Brief explanation of the ruling based on contract terms')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='accounts.dispute')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dispute', 'lawyer')},
            },
        ),
    ]
