# Generated by Django 6.0.7 on 2026-07-17 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merchantapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='contract',
            field=models.OneToOneField(
                on_delete=models.deletion.CASCADE, 
                primary_key=False, 
                to='accounts.contract', 
                to_field='contract_id'
            ),
        ),
    ]
